services:
  swagger-ui:
      image: swaggerapi/swagger-ui
      container_name: ods_docs
      ports:
        - "8080:8080"
      environment:
        SWAGGER_JSON: /tmp/contract.yaml
      volumes:
        - ./ods_api_contract.yaml:/tmp/contract.yaml:ro
  db:
    image: mysql:8.0
    container_name: ods_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ods_db_data:/var/lib/mysql

volumes:
  ods_db_data: