-- Tabelas de Domínio (Lookup Tables)
CREATE TABLE AREAS_FORMACAO (
    afm_id INT NOT NULL AUTO_INCREMENT,
    afm_nome VARCHAR(150) NOT NULL,
    CONSTRAINT PK_AFM PRIMARY KEY (afm_id)
) COMMENT 'Tabela de áreas de formação';

CREATE TABLE CADEIAS_PRODUTIVAS (
    cdp_id INT NOT NULL AUTO_INCREMENT,
    cdp_nome VARCHAR(25) NOT NULL,
    CONSTRAINT PK_CDP PRIMARY KEY (cdp_id)
) COMMENT 'Tabela de cadeias produtivas';

CREATE TABLE CIDADES_RESIDENCIAS (
    cid_id INT NOT NULL AUTO_INCREMENT,
    cid_nome VARCHAR(200) NOT NULL,
    CONSTRAINT PK_CID PRIMARY KEY (cid_id)
) COMMENT 'Tabela de cidades de residência';

CREATE TABLE DEFICIENCIAS (
    def_id INT NOT NULL AUTO_INCREMENT,
    def_nome VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DEF PRIMARY KEY (def_id)
) COMMENT 'Tabela de deficiências';

CREATE TABLE EIXOS_ODS (
    eos_id INT NOT NULL AUTO_INCREMENT,
    eos_nome VARCHAR(50) NOT NULL,
    eos_descricao VARCHAR(500) NOT NULL,
    CONSTRAINT PK_EOS PRIMARY KEY (eos_id)
) COMMENT 'Eixos da ODS';

CREATE TABLE IDENTIDADES_GENERO (
    idg_id INT NOT NULL AUTO_INCREMENT,
    idg_nome VARCHAR(50) NOT NULL,
    CONSTRAINT PK_IDG PRIMARY KEY (idg_id)
) COMMENT 'Identidade de gênero';

CREATE TABLE INSTITUICOES_VINCULOS (
    itv_id INT NOT NULL AUTO_INCREMENT,
    itv_nome VARCHAR(200) NOT NULL,
    CONSTRAINT PK_ITV PRIMARY KEY (itv_id)
) COMMENT 'Instituições de vínculo';

CREATE TABLE ORIENTACOES_SEXUAIS (
    ors_id INT NOT NULL AUTO_INCREMENT,
    ors_nome VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ORS PRIMARY KEY (ors_id)
) COMMENT 'Orientações sexuais';

CREATE TABLE PUBLICOS_FATEC (
    pub_id INT NOT NULL AUTO_INCREMENT,
    pub_nome VARCHAR(150) NOT NULL,
    CONSTRAINT PK_PUB PRIMARY KEY (pub_id)
) COMMENT 'Públicos da Fatec';

CREATE TABLE RACAS_CORES (
    rcr_id INT NOT NULL AUTO_INCREMENT,
    rcr_nome VARCHAR(50) NOT NULL,
    CONSTRAINT PK_RCR PRIMARY KEY (rcr_id)
) COMMENT 'Raças e cores';

CREATE TABLE REGIOES (
    reg_id INT NOT NULL AUTO_INCREMENT,
    reg_nome VARCHAR(50) NOT NULL,
    CONSTRAINT PK_REG PRIMARY KEY (reg_id)
) COMMENT 'Regiões';

CREATE TABLE TIPOS_PARTICIPANTES (
    tpp_id INT NOT NULL AUTO_INCREMENT,
    tpp_descricao VARCHAR(30) NOT NULL,
    CONSTRAINT PK_TPP PRIMARY KEY (tpp_id)
) COMMENT 'Tipos de participante';

-- 2. Tabela Principal: PARTICIPANTES
CREATE TABLE PARTICIPANTES (
    par_id INT NOT NULL AUTO_INCREMENT,
    par_nome VARCHAR(250) NOT NULL,
    par_mail VARCHAR(80) NOT NULL UNIQUE,
    par_fone CHAR(11) NOT NULL,
    par_data_conferencia DATE NOT NULL,
    par_recs_acessibilidade VARCHAR(1000), 
    par_ocupacao VARCHAR(200) NOT NULL,
    par_tpp_id INT NOT NULL,
    par_idg_id INT NOT NULL,
    par_ors_id INT NOT NULL,
    par_rcr_id INT NOT NULL,
    par_cid_id INT NOT NULL,
    par_cid_outro VARCHAR(200),
    par_autorizacao CHAR(1) NOT NULL,
    par_reg_id INT NOT NULL,
    par_itv_id INT NOT NULL,
    par_itv_outro VARCHAR(200),
    par_cert_enviado BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT PK_PAR PRIMARY KEY (par_id),
    CONSTRAINT FK_PAR_CID FOREIGN KEY (par_cid_id) REFERENCES CIDADES_RESIDENCIAS (cid_id),
    CONSTRAINT FK_PAR_IDG FOREIGN KEY (par_idg_id) REFERENCES IDENTIDADES_GENERO (idg_id),
    CONSTRAINT FK_PAR_ORS FOREIGN KEY (par_ors_id) REFERENCES ORIENTACOES_SEXUAIS (ors_id),
    CONSTRAINT FK_PAR_RCR FOREIGN KEY (par_rcr_id) REFERENCES RACAS_CORES (rcr_id),
    CONSTRAINT FK_PAR_REG FOREIGN KEY (par_reg_id) REFERENCES REGIOES (reg_id),
    CONSTRAINT FK_PAR_TPP FOREIGN KEY (par_tpp_id) REFERENCES TIPOS_PARTICIPANTES (tpp_id),
    CONSTRAINT FK_PAR_ITV FOREIGN KEY (par_itv_id) REFERENCES INSTITUICOES_VINCULOS (itv_id)
);

-- 3. Tabela de PROPOSTAS e VOTAÇÕES
CREATE TABLE PROPOSTAS (
    prp_id INT NOT NULL AUTO_INCREMENT,
    prp_titulo VARCHAR(150) NOT NULL,
    prp_descricao VARCHAR(2000) NOT NULL,
    prp_autor VARCHAR(200),
    prp_autor_email VARCHAR(300),
    prp_eos_id INT NOT NULL,
    prp_data DATE NOT NULL DEFAULT '2026-04-04',
    CONSTRAINT PK_PRP PRIMARY KEY (prp_id),
    CONSTRAINT FK_PRP_EOS FOREIGN KEY (prp_eos_id) REFERENCES EIXOS_ODS (eos_id)
);

CREATE TABLE VOTACOES (
    vot_par_id INT NOT NULL,
    vot_prp_id INT NOT NULL,
    vot_data DATE NOT NULL,
    CONSTRAINT PK_VOT PRIMARY KEY (vot_par_id, vot_prp_id),
    CONSTRAINT FK_VOT_PAR FOREIGN KEY (vot_par_id) REFERENCES PARTICIPANTES (par_id),
    CONSTRAINT FK_VOT_PRP FOREIGN KEY (vot_prp_id) REFERENCES PROPOSTAS (prp_id)
);

-- Tabelas Associativas (N:N)
CREATE TABLE DEFICIENCIAS_PARTICIPANTES (
    dfp_def_id INT NOT NULL,
    dfp_par_id INT NOT NULL,
    CONSTRAINT PK_DFP PRIMARY KEY (dfp_def_id, dfp_par_id),
    CONSTRAINT FK_DFP_DEF FOREIGN KEY (dfp_def_id) REFERENCES DEFICIENCIAS (def_id),
    CONSTRAINT FK_DFP_PAR FOREIGN KEY (dfp_par_id) REFERENCES PARTICIPANTES (par_id)
);

CREATE TABLE PARTICIPANTES_AREAS (
    ppa_par_id INT NOT NULL,
    ppa_afm_id INT NOT NULL,
    CONSTRAINT PK_PPA PRIMARY KEY (ppa_par_id, ppa_afm_id),
    CONSTRAINT FK_PPA_AFM FOREIGN KEY (ppa_afm_id) REFERENCES AREAS_FORMACAO (afm_id),
    CONSTRAINT FK_PPA_PAR FOREIGN KEY (ppa_par_id) REFERENCES PARTICIPANTES (par_id)
);

CREATE TABLE PARTICIPANTES_CADS_PRODUTIVAS (
    pcp_cdp_id INT NOT NULL,
    pcp_par_id INT NOT NULL,
    CONSTRAINT PK_PCP PRIMARY KEY (pcp_cdp_id, pcp_par_id),
    CONSTRAINT FK_PCP_CDP FOREIGN KEY (pcp_cdp_id) REFERENCES CADEIAS_PRODUTIVAS (cdp_id),
    CONSTRAINT FK_PCP_PAR FOREIGN KEY (pcp_par_id) REFERENCES PARTICIPANTES (par_id)
);

CREATE TABLE PARTICIPANTES_EIXOS (
    ppe_eos_id INT NOT NULL,
    ppe_par_id INT NOT NULL,
    CONSTRAINT PK_PPE PRIMARY KEY (ppe_eos_id, ppe_par_id),
    CONSTRAINT FK_PPE_EOS FOREIGN KEY (ppe_eos_id) REFERENCES EIXOS_ODS (eos_id),
    CONSTRAINT FK_PPS_PAR FOREIGN KEY (ppe_par_id) REFERENCES PARTICIPANTES (par_id)
);

CREATE TABLE PARTICIPANTES_PUBLICOS (
    ppb_pub_id INT NOT NULL,
    ppb_par_id INT NOT NULL,
    CONSTRAINT PK_PPB PRIMARY KEY (ppb_pub_id, ppb_par_id),
    CONSTRAINT FK_PPB_PAR FOREIGN KEY (ppb_par_id) REFERENCES PARTICIPANTES (par_id),
    CONSTRAINT FK_PPB_PUB FOREIGN KEY (ppb_pub_id) REFERENCES PUBLICOS_FATEC (pub_id)
);